### ISSUE TITLE
Level 3 (dark magic demon level) very hard to make through due to slider time interval constraints

### ISSUE THREAD

**Issue by CoffeeDev7** [tdot123-1/untitled-ninja-game#1]
The long blick slider in the middle will be lower for some seconds and then changes **instantly** to a higher level. The player on the slider when on slider will automatically fall down because of this!
Solution: There should be either two long sliders or **the slider in question should take the player too with it when it changes** its level(low to high viceversa)
i dont know if this was intentional by the author.But considering only 5 lives and slider stays in same state for only ~5seconds this is could be hard for beginners. they need 10 lives for 3rd level i think.

**Comment by CoffeeDev7** [comment]
I'm closing the issue after playing with more lives configured and realising its not impossible but instead hard with the present lives and slider time intervals. I'm guessing this was intentional by the author.

**Comment by tdot123-1** [comment]
Hi there, thank you for playing my game! You are correct my intention was to make this level more challenging with the changing platforms, but not impossible. My idea was that the player would eventually recognize the pattern and figure out when to jump on the platform and when it is too late. I might add some sort of indicator when the platform is about to change (like change its color or start blinking or something) to make it more fair. Thanks for pointing this out.

**Comment by CoffeeDev7** [comment]
yeah thanks
